ALTER TABLE users ADD COLUMN level INT DEFAULT 1;
ALTER TABLE users ADD COLUMN points INT DEFAULT 0;
ALTER TABLE users ADD COLUMN show_notes_count BOOLEAN DEFAULT TRUE;
ALTER TABLE users ADD COLUMN show_friends_count BOOLEAN DEFAULT TRUE;
ALTER TABLE users ADD COLUMN show_projects_count BOOLEAN DEFAULT TRUE;
